# Generated by Django 3.2.9 on 2021-11-19 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='no title', max_length=300)),
                ('img', models.FileField(default='error', upload_to='clips/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
