# Generated by Django 3.2.9 on 2021-11-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(default='error', upload_to='glasstrove/'),
        ),
    ]
