# Generated by Django 2.2.24 on 2021-12-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211225_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
