# Generated by Django 2.2.24 on 2022-01-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.CharField(default='No Creator', max_length=600),
        ),
    ]
