# Generated by Django 2.2.24 on 2022-01-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.CharField(blank=True, default='No Creator', max_length=600),
        ),
    ]
