# version: "3.9"
   
# services:
  
#   server:
#     build: ./server
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./server:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
    
# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    expose:
      - 8000
    depends_on:
      - db

  frontend:
    stdin_open: true
    build: ./web
    volumes:
      - ./web:/usr/src/app
      - /web/src/app/node_modules
    expose:
      - 3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend
      - db