# Generated by Django 3.2.9 on 2021-12-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
